# Supabase Local Dev Config — Trifivend
# Apps: FastAPI @ 127.0.0.1:8080, Streamlit @ 127.0.0.1:8501
project_id = "trifivend"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql", "./policies.sql"]

[db.network_restrictions]
enabled = false
allowed_cidrs = ["0.0.0.0/0"]
allowed_cidrs_v6 = ["::/0"]

[realtime]
enabled = true
# Your Fly private mesh is IPv6-first; mirror that in local dev for parity.
ip_version = "IPv6"

[studio]
enabled = true
port = 54323
# IMPORTANT: Studio talks to PostgREST via supabase API; include the port.
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

# App needs a bucket for synthesized audio; private by default.
[storage.buckets.audio]
public = false
file_size_limit = "50MiB"
allowed_mime_types = ["audio/mpeg", "audio/mp3"]
objects_path = "./.storage/audio"

[auth]
enabled = true

# Local dev UI is Streamlit (default 8501). Add Next.js 3000 if you use it locally too.
site_url = "http://127.0.0.1:8501"
additional_redirect_urls = ["http://127.0.0.1:3000", "http://localhost:8501", "http://localhost:3000"]

jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false
minimum_password_length = 6
password_requirements = ""

[auth.rate_limit]
email_sent = 2
sms_sent = 30
anonymous_users = 30
token_refresh = 150
sign_in_sign_ups = 30
token_verifications = 30
web3 = 30

# Example Twilio auth binding (disabled locally)
[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
auth_token = "env(SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN)"

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 8083
deno_version = 2

[analytics]
enabled = true
port = 54327
backend = "postgres"

[experimental]
orioledb_version = ""
s3_host = "env(S3_HOST)"
s3_region = "env(S3_REGION)"
s3_access_key = "env(S3_ACCESS_KEY)"
s3_secret_key = "env(S3_SECRET_KEY)"