# Fly Machines config for the UI (trifivend-ui)
app = "trifivend-ui"
primary_region = "sjc"

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

[checks]
  # Adjust path to any lightweight 200 OK route your UI serves
  [checks.health]
    type     = "http"
    port     = 8080
    method   = "GET"
    path     = "/"
    interval = "15s"
    timeout  = "3s"
