# fly.api.toml — FastAPI backend (Machines / Apps V2)
app = "ai-callbot"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"
  # If you're using the monorepo dep split, uncomment:
  # [build.args]
  #   REQS = "/tmp/requirements.backend.txt"

[env]
  PORT = "8080"
  APP_BASE_URL = "https://ai-callbot.fly.dev"

[http_service]
  # Must match the port your app listens on (uvicorn ... --port 8080)
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false     # keep running while stabilizing
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 150
    hard_limit = 200

  # Health check: keep this SHALLOW (/health returns static JSON)
  [[http_service.checks]]
    name = "api-health"
    method = "GET"
    path = "/health"
    interval = "5s"
    timeout = "2s"
    grace_period = "120s"        # generous during rollout; tighten later
