app = "trifivend-ui"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    REQS = "/tmp/requirements.ui.txt" # <-- installs Streamlit

[processes]
  ui = "python -m streamlit run ui/streamlit_app.py --server.address 0.0.0.0 --server.port 8501"

[[services]]
  protocol = "tcp"
  internal_port = 8501
  processes = ["ui"]
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls","http"]
    port = 443

[[checks]]
  type = "http"
  name = "ui-health"
  port = 8501
  interval = "5s"
  timeout = "2s"
  grace_period = "30s"
  method = "get"
  path = "/"
