app = "ai-callbot"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    REQS = "/tmp/requirements.backend.txt"

[processes]
  api = "uvicorn main:app --host 0.0.0.0 --port 8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["api"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout  = "2s"
    grace_period = "60s"