[http_service]
  internal_port = 8080
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

  [[http_service.checks]]
    name = "api-health"
    method = "GET"
    path = "/health"
    interval = "5s"
    timeout = "2s"
    grace_period = "60s"