app = "trifivend-ui"          # <-- your UI app name
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    REQS = "/tmp/requirements.ui.txt"

[env]
  STREAMLIT_SERVER_HEADLESS = "true"
  STREAMLIT_SERVER_ADDRESS  = "0.0.0.0"
  STREAMLIT_SERVER_PORT     = "8501"

[processes]
  ui = "streamlit run ui/streamlit_app.py --server.address 0.0.0.0 --server.port 8501"

[[services]]
  protocol = "tcp"
  internal_port = 8501
  processes = ["ui"]

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls","http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout  = "2s"
    grace_period = "30s"
