app = "trifivend-ui"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    REQS = "/tmp/requirements.ui.txt"

# kill START_CMD. Let Fly run the process.
[processes]
  ui = "streamlit run ui/streamlit_app.py --server.address 0.0.0.0 --server.port 8501"

[[services]]
  protocol = "tcp"
  internal_port = 8501
  processes = ["ui"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout  = "2s"
    grace_period = "30s"