[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1

[checks.http]
  port = 8080
  type = "http"
  interval = "10s"
  timeout = "2s"
  method = "GET"
  path = "/health"