# fly.api.toml — ai-callbot (backend)
app = "ai-callbot"
primary_region = "sjc"

[env]
  PORT = "8080"
  APP_BASE_URL = "https://ai-callbot.fly.dev"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 150

# Health check with a gentle grace period so logs don't flap during boot
[[checks]]
  type = "http"
  name = "api-health"
  port = 8080
  interval = "5s"
  timeout = "2s"
  grace_period = "40s"
  method = "get"
  path = "/health"