# fly.ui.toml — example if you host UI on Fly too
app = "trifivend-ui"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile" # or use a separate UI Dockerfile in /ui

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[checks]]
  type = "http"
  name = "ui-health"
  port = 3000
  interval = "5s"
  timeout = "2s"
  grace_period = "30s"
  method = "get"
  path = "/"