app = "ai-callbot"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    REQS = "/tmp/requirements.backend.txt"

[processes]
  # If your app lives at app/main.py, change to: uvicorn app.main:app ...
  api = "uvicorn main:app --host 0.0.0.0 --port 8080"

[[services]]
  processes = ["api"]
  protocol = "tcp"
  internal_port = 8080

  # Public endpoints
  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Prefer HTTP health (FastAPI route you expose)
  [[services.http_checks]]
    method = "GET"
    path = "/health"
    interval = "10s"
    timeout  = "2s"
    grace_period = "60s"

  # Backstop TCP check
  [[services.tcp_checks]]
    interval = "15s"
    timeout  = "2s"
    grace_period = "60s"

  # Concurrency guardrails
  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 40