app = "ai-vendbot"            # <-- your API app name
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    REQS = "/tmp/requirements.backend.txt"

[env]
  PORT = "8080"

[processes]
  api = "uvicorn app.main:app --host 0.0.0.0 --port 8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["api"]

  # Public ports only if you need Twilio/webhooks/external access
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls","http"]
    port = 443

  [[services.http_checks]]
    interval = "15s"
    timeout  = "2s"
    method   = "GET"
    path     = "/health"
    protocol = "http"
    grace_period = "30s"
