app = "ai-vendbot"
primary_region = "sjc"

[env]
  PORT = "8080"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1