name: backend-ci

on:
  push:
    paths:
      - "**.py"
      - "requirements.backend.txt"
      - "Dockerfile"
      - ".github/workflows/backend-ci.yml"
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.backend.txt
          # lightweight test deps if you have tests
          pip install pytest pytest-asyncio

      - name: Static checks
        run: |
          python -m pip install ruff
          ruff check .

      - name: Unit tests
        run: |
          if [ -d "tests" ]; then pytest -q; else echo "No tests, skipping"; fi

      - name: Build Docker image
        run: |
          docker build -t trifivend-api:ci .
