name: deploy-vercel
on:
  push: { branches: [ main ] }
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  vercel:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # project targeting the /ui dir
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel env
        run: vercel pull --yes --environment=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        run: vercel build --cwd ui --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            vercel deploy --prebuilt --cwd ui --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --prebuilt --cwd ui --token=${{ secrets.VERCEL_TOKEN }}
          fi
